description: "ENCODE Guidelines"
email: "federico.aurora@ub.uio.no"
mailing_list: "https://site.unibo.it/encode/en/agenda/epidoc-workshop/community"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
